services:
  cfcgs_tracker_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  cfcgs_tracker:
    image: cfcgs_tracker
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - cfcgs_tracker_database
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata: