services:
  cfcgs_tracker_database:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Belem
      PGTZ: America/Belem
    ports:
      - "5432:5432"

  cfcgs_tracker:
    image: cfcgs_tracker
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8001:8000"
    depends_on:
      - cfcgs_tracker_database
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@cfcgs_tracker_database:5432/${DB_NAME}
      INITIAL_ADMIN_USERNAME: ${INITIAL_ADMIN_USERNAME}
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}

volumes:
  pgdata:
