"""adding adaptation and mitigation fields in Commitment

Revision ID: 3fc63392a77d
Revises: 297068f885a6
Create Date: 2025-07-30 18:23:04.472886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc63392a77d'
down_revision: Union[str, None] = '297068f885a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('adaptation_amount_usd_thousand', sa.Float(), nullable=True))
    op.add_column('commitments', sa.Column('mitigation_amount_usd_thousand', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commitments', 'mitigation_amount_usd_thousand')
    op.drop_column('commitments', 'adaptation_amount_usd_thousand')
    # ### end Alembic commands ###