"""refactoring models

Revision ID: 89f298e09e39
Revises: 39f944ab0694
Create Date: 2026-06-20 22:20:51.139277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f298e09e39'
down_revision: Union[str, None] = '39f944ab0694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS view_commitments_detailed;")
    op.create_table('beneficiary_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('financial_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('funding_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('csv', 'xlsx', name='filetype'), nullable=False),
    sa.Column('status', sa.Enum('success', 'processing', 'error', name='importstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_fund_profiles',
    sa.Column('funding_provider_id', sa.Integer(), nullable=False),
    sa.Column('fund_type_id', sa.Integer(), nullable=True),
    sa.Column('fund_focus_id', sa.Integer(), nullable=True),
    sa.Column('pledge', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('approval', sa.Float(), nullable=True),
    sa.Column('disbursement', sa.Float(), nullable=True),
    sa.Column('projects_approved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fund_focus_id'], ['fund_focuses.id'], ),
    sa.ForeignKeyConstraint(['fund_type_id'], ['fund_types.id'], ),
    sa.ForeignKeyConstraint(['funding_provider_id'], ['funding_providers.id'], ),
    sa.PrimaryKeyConstraint('funding_provider_id')
    )
    op.create_table('sub_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('climate_finance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('approved_amount_usd_millions', sa.Float(), nullable=True),
    sa.Column('climate_finance_amount_usd_millions', sa.Float(), nullable=True),
    sa.Column('adaptation_amount_usd_millions', sa.Float(), nullable=True),
    sa.Column('mitigation_amount_usd_millions', sa.Float(), nullable=True),
    sa.Column('both_objectives_amount_usd_millions', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('funding_provider_id', sa.Integer(), nullable=True),
    sa.Column('financial_instrument_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('sub_sector_id', sa.Integer(), nullable=True),
    sa.Column('beneficiary_country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_country_id'], ['beneficiary_countries.id'], ),
    sa.ForeignKeyConstraint(['financial_instrument_id'], ['financial_instruments.id'], ),
    sa.ForeignKeyConstraint(['funding_provider_id'], ['funding_providers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['sub_sector_id'], ['sub_sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_commitments_channel_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_project_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_provider_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_recipient_country_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_year'), table_name='commitments')
    op.drop_table('commitments')
    op.add_column('projects', sa.Column('title', sa.String(), nullable=False))
    op.drop_index(op.f('ix_projects_country_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_fund_id'), table_name='projects')
    op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
    op.create_unique_constraint(None, 'projects', ['title'])
    op.drop_constraint(op.f('projects_country_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_fund_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'fund_id')
    op.drop_column('projects', 'name')
    op.drop_column('projects', 'country_id')
    op.drop_table('funds')
    op.drop_table('funding_entities')
    op.drop_index(op.f('ix_countries_region_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('regions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_fund_id_fkey'), 'projects', 'funds', ['fund_id'], ['id'])
    op.create_foreign_key(op.f('projects_country_id_fkey'), 'projects', 'countries', ['country_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_projects_fund_id'), 'projects', ['fund_id'], unique=False)
    op.create_index(op.f('ix_projects_country_id'), 'projects', ['country_id'], unique=False)
    op.drop_column('projects', 'title')
    op.create_table('funds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('funds_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fund_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fund_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fund_focus_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pledge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('approval', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('disbursement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('projects_approved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_focus_id'], ['fund_focuses.id'], name='funds_fund_focus_id_fkey'),
    sa.ForeignKeyConstraint(['fund_type_id'], ['fund_types.id'], name='funds_fund_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='funds_pkey'),
    sa.UniqueConstraint('fund_name', name='funds_fund_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('regions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='regions_pkey'),
    sa.UniqueConstraint('name', name='regions_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('commitments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_usd_thousand', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recipient_country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adaptation_amount_usd_thousand', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mitigation_amount_usd_thousand', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overlap_amount_usd_thousand', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['funding_entities.id'], name=op.f('commitments_channel_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('commitments_project_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['funding_entities.id'], name=op.f('commitments_provider_id_fkey')),
    sa.ForeignKeyConstraint(['recipient_country_id'], ['countries.id'], name=op.f('commitments_recipient_country_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('commitments_pkey'))
    )
    op.create_index(op.f('ix_commitments_year'), 'commitments', ['year'], unique=False)
    op.create_index(op.f('ix_commitments_recipient_country_id'), 'commitments', ['recipient_country_id'], unique=False)
    op.create_index(op.f('ix_commitments_provider_id'), 'commitments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_commitments_project_id'), 'commitments', ['project_id'], unique=False)
    op.create_index(op.f('ix_commitments_channel_id'), 'commitments', ['channel_id'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('countries_region_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('countries_pkey')),
    sa.UniqueConstraint('name', name=op.f('countries_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_countries_region_id'), 'countries', ['region_id'], unique=False)
    op.create_table('funding_entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('funding_entities_pkey')),
    sa.UniqueConstraint('name', name=op.f('funding_entities_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('climate_finance_records')
    op.drop_table('sub_sectors')
    op.drop_table('provider_fund_profiles')
    op.drop_table('import_jobs')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('sectors')
    op.drop_table('funding_providers')
    op.drop_table('financial_instruments')
    op.drop_table('beneficiary_countries')
    # ### end Alembic commands ###
