"""adding funds, fund_types and fun_focuses tables

Revision ID: 9ed181776bdf
Revises: 
Create Date: 2025-05-20 22:40:22.128134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed181776bdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_focuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fund_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('fund_type_id', sa.Integer(), nullable=False),
    sa.Column('fund_focus_id', sa.Integer(), nullable=False),
    sa.Column('pledge', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('approval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fund_focus_id'], ['fund_focuses.id'], ),
    sa.ForeignKeyConstraint(['fund_type_id'], ['fund_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funds')
    op.drop_table('fund_types')
    op.drop_table('fund_focuses')
    # ### end Alembic commands ###
