"""Adiciona overlap_amount na tabela commitment

Revision ID: a33ce1dd3cc1
Revises: ebb853265f83
Create Date: 2025-10-23 00:13:24.742376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33ce1dd3cc1'
down_revision: Union[str, None] = 'ebb853265f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('overlap_amount_usd_thousand', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commitments', 'overlap_amount_usd_thousand')
    # ### end Alembic commands ###
