"""adding file_type in ImportJob

Revision ID: c8b66f400d8a
Revises: 89f298e09e39
Create Date: 2026-06-21 20:22:26.500838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b66f400d8a'
down_revision: Union[str, None] = '89f298e09e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('file_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'file_name')
    # ### end Alembic commands ###
