"""adding index

Revision ID: ebb853265f83
Revises: 3fc63392a77d
Create Date: 2025-08-01 09:24:15.177475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb853265f83'
down_revision: Union[str, None] = '3fc63392a77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_commitments_channel_id'), 'commitments', ['channel_id'], unique=False)
    op.create_index(op.f('ix_commitments_project_id'), 'commitments', ['project_id'], unique=False)
    op.create_index(op.f('ix_commitments_provider_id'), 'commitments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_commitments_recipient_country_id'), 'commitments', ['recipient_country_id'], unique=False)
    op.create_index(op.f('ix_commitments_year'), 'commitments', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitments_year'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_recipient_country_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_provider_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_project_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_channel_id'), table_name='commitments')
    # ### end Alembic commands ###
